package acib_acitboa;

use strict;
use feature 'unicode_strings';
use export::Testdata;
use tdms_conf qw($export_prefix);

our @ISA = qw(Testdata);

our $filename = "$export_prefix.ACIB.ACITBOA";

# Indicates field length and if sign should be applied
# Third element is for sorting
our %acib_acitboa = (
    boa_org_num            => [ 11, 1,   0 ],
    boa_slut_kod           => [ 1 , 0,   1 ],
    boa_slut_typ           => [ 1 , 0,   2 ],
    boa_redov_typ          => [ 1 , 0,   3 ],
    boa_redov_kod          => [ 1 , 0,   4 ],
    boa_slut_per           => [ 6 , 1,   5 ],
    boa_laengd_ant         => [ 2 , 1,   6 ],
    boa_status_kod         => [ 1 , 0,   7 ],
    boa_slutakt_kod        => [ 1 , 0,   8 ],
    boa_utskr_dat          => [ 8 , 1,   9 ],
    boa_ny_sig             => [ 4 , 0,  10 ],
    boa_trans_dat          => [ 8 , 1,  11 ],
    boa_tid                => [ 6 , 1,  12 ],
    boa_uppd_sig           => [ 4 , 0,  13 ],
    boa_post_status        => [ 1 , 1,  14 ],
    boa_kassett_num        => [ 4 , 1,  15 ],
    boa_filmruta_num       => [ 4 , 1,  16 ],
    boa_ab_status          => [ 1 , 0,  17 ],
    boa_brist_kod          => [ 1 , 0,  18 ],
    boa_kommit_namn        => [ 48, 0,  19 ],
    boa_kommit_org_num     => [ 11, 1,  20 ],
    boa_utdeln_kod         => [ 1 , 0,  21 ],
    boa_utdeln_bel         => [ 9 , 1,  22 ],
    boa_totfakt_bel        => [ 9 , 1,  23 ],
    boa_totfakt_kod        => [ 1 , 0,  24 ],
    boa_foers_bel          => [ 9 , 1,  25 ],
    boa_foers_kod          => [ 1 , 0,  26 ],
    boa_kostvaror_bel      => [ 9 , 1,  27 ],
    boa_kostvaror_kod      => [ 1 , 0,  28 ],
    boa_bruttores_bel      => [ 9 , 1,  29 ],
    boa_bruttores_kod      => [ 1 , 0,  30 ],
    boa_foerskost_bel      => [ 9 , 1,  31 ],
    boa_foerskost_kod      => [ 1 , 0,  32 ],
    boa_admkost_bel        => [ 9 , 1,  33 ],
    boa_admkost_kod        => [ 1 , 0,  34 ],
    boa_foukost_bel        => [ 9 , 1,  35 ],
    boa_foukost_kod        => [ 1 , 0,  36 ],
    boa_jfrpostr2_bel      => [ 9 , 1,  37 ],
    boa_jfrpostr2_kod      => [ 1 , 0,  38 ],
    boa_oeroerinr2_bel     => [ 9 , 1,  39 ],
    boa_oeroerinr2_kod     => [ 1 , 0,  40 ],
    boa_oeroerkor2_bel     => [ 9 , 1,  41 ],
    boa_oeroerkor2_kod     => [ 1 , 0,  42 ],
    boa_foerlager_bel      => [ 9 , 1,  43 ],
    boa_foerlager_kod      => [ 1 , 0,  44 ],
    boa_aktivarb_bel       => [ 9 , 1,  45 ],
    boa_aktivarb_kod       => [ 1 , 0,  46 ],
    boa_oeroerinr1_bel     => [ 9 , 1,  47 ],
    boa_oeroerinr1_kod     => [ 1 , 0,  48 ],
    boa_raavaror_bel       => [ 9 , 1,  49 ],
    boa_raavaror_kod       => [ 1 , 0,  50 ],
    boa_handvaror_bel      => [ 9 , 1,  51 ],
    boa_handvaror_kod      => [ 1 , 0,  52 ],
    boa_oevrextko_bel      => [ 9 , 1,  53 ],
    boa_oevrextko_kod      => [ 1 , 0,  54 ],
    boa_perskost_bel       => [ 9 , 1,  55 ],
    boa_perskost_kod       => [ 1 , 0,  56 ],
    boa_avskrivn_bel       => [ 9 , 1,  57 ],
    boa_avskrivn_kod       => [ 1 , 0,  58 ],
    boa_jfrpostr1_bel      => [ 9 , 1,  59 ],
    boa_jfrpostr1_kod      => [ 1 , 0,  60 ],
    boa_oeroerkor1_bel     => [ 9 , 1,  61 ],
    boa_oeroerkor1_kod     => [ 1 , 0,  62 ],
    boa_roerres_bel        => [ 9 , 1,  63 ],
    boa_roerres_kod        => [ 1 , 0,  64 ],
    boa_resandkcn_bel      => [ 9 , 1,  65 ],
    boa_resandkcn_kod      => [ 1 , 0,  66 ],
    boa_rteintkcn_bel      => [ 9 , 1,  67 ],
    boa_rteintkcn_kod      => [ 1 , 0,  68 ],
    boa_extrteint_bel      => [ 9 , 1,  69 ],
    boa_extrteint_kod      => [ 1 , 0,  70 ],
    boa_oevrfinint_bel     => [ 9 , 1,  71 ],
    boa_oevrfinint_kod     => [ 1 , 0,  72 ],
    boa_rtekostkcn_bel     => [ 9 , 1,  73 ],
    boa_rtekostkcn_kod     => [ 1 , 0,  74 ],
    boa_extrtekost_bel     => [ 9 , 1,  75 ],
    boa_extrtekost_kod     => [ 1 , 0,  76 ],
    boa_oevrfinko_bel      => [ 9 , 1,  77 ],
    boa_oevrfinko_kod      => [ 1 , 0,  78 ],
    boa_jfrfinpost_bel     => [ 9 , 1,  79 ],
    boa_jfrfinpost_kod     => [ 1 , 0,  80 ],
    boa_resfinko_bel       => [ 9 , 1,  81 ],
    boa_resfinko_kod       => [ 1 , 0,  82 ],
    boa_exoint_bel         => [ 9 , 1,  83 ],
    boa_exoint_kod         => [ 1 , 0,  84 ],
    boa_exokost_bel        => [ 9 , 1,  85 ],
    boa_exokost_kod        => [ 1 , 0,  86 ],
    boa_kcnbidragr_bel     => [ 9 , 1,  87 ],
    boa_kcnbidragr_kod     => [ 1 , 0,  88 ],
    boa_aegtillskr_bel     => [ 9 , 1,  89 ],
    boa_aegtillskr_kod     => [ 1 , 0,  90 ],
    boa_bokdisp_bel        => [ 9 , 1,  91 ],
    boa_bokdisp_kod        => [ 1 , 0,  92 ],
    boa_skatt_bel          => [ 9 , 1,  93 ],
    boa_skatt_kod          => [ 1 , 0,  94 ],
    boa_minintrr_bel       => [ 9 , 1,  95 ],
    boa_minintrr_kod       => [ 1 , 0,  96 ],
    boa_resultatr_bel      => [ 9 , 1,  97 ],
    boa_resultatr_kod      => [ 1 , 0,  98 ],
    boa_tecknkap_bel       => [ 9 , 1,  99 ],
    boa_tecknkap_kod       => [ 1 , 0, 100 ],
    boa_balutgfou_bel      => [ 9 , 1, 101 ],
    boa_balutgfou_kod      => [ 1 , 0, 102 ],
    boa_patent_bel         => [ 9 , 1, 103 ],
    boa_patent_kod         => [ 1 , 0, 104 ],
    boa_goodwill_bel       => [ 9 , 1, 105 ],
    boa_goodwill_kod       => [ 1 , 0, 106 ],
    boa_oeimanlti_bel      => [ 9 , 1, 107 ],
    boa_oeimanlti_kod      => [ 1 , 0, 108 ],
    boa_sumimanlti_bel     => [ 9 , 1, 109 ],
    boa_sumimanlti_kod     => [ 1 , 0, 110 ],
    boa_byggmark_bel       => [ 9 , 1, 111 ],
    boa_byggmark_kod       => [ 1 , 0, 112 ],
    boa_mark_bel           => [ 9 , 1, 113 ],
    boa_mark_kod           => [ 1 , 0, 114 ],
    boa_maskiner_bel       => [ 9 , 1, 115 ],
    boa_maskiner_kod       => [ 1 , 0, 116 ],
    boa_invent_bel         => [ 9 , 1, 117 ],
    boa_invent_kod         => [ 1 , 0, 118 ],
    boa_maskinv_bel        => [ 9 , 1, 119 ],
    boa_maskinv_kod        => [ 1 , 0, 120 ],
    boa_eavmatanti_bel     => [ 9 , 1, 121 ],
    boa_eavmatanti_kod     => [ 1 , 0, 122 ],
    boa_avmatanti_bel      => [ 9 , 1, 123 ],
    boa_avmatanti_kod      => [ 1 , 0, 124 ],
    boa_summatanti_bel     => [ 9 , 1, 125 ],
    boa_summatanti_kod     => [ 1 , 0, 126 ],
    boa_andelikcn_bel      => [ 9 , 1, 127 ],
    boa_andelikcn_kod      => [ 1 , 0, 128 ],
    boa_fordrkcn_bel       => [ 9 , 1, 129 ],
    boa_fordrkcn_kod       => [ 1 , 0, 130 ],
    boa_laandelaeg_bel     => [ 9 , 1, 131 ],
    boa_laandelaeg_kod     => [ 1 , 0, 132 ],
    boa_oefinanti_bel      => [ 9 , 1, 133 ],
    boa_oefinanti_kod      => [ 1 , 0, 134 ],
    boa_sumfinanti_bel     => [ 9 , 1, 135 ],
    boa_sumfinanti_kod     => [ 1 , 0, 136 ],
    boa_sumanti_bel        => [ 9 , 1, 137 ],
    boa_sumanti_kod        => [ 1 , 0, 138 ],
    boa_arbfann_bel        => [ 9 , 1, 139 ],
    boa_arbfann_kod        => [ 1 , 0, 140 ],
    boa_oevarulag_bel      => [ 9 , 1, 141 ],
    boa_oevarulag_kod      => [ 1 , 0, 142 ],
    boa_sumvarulag_bel     => [ 9 , 1, 143 ],
    boa_sumvarulag_kod     => [ 1 , 0, 144 ],
    boa_kundford_bel       => [ 9 , 1, 145 ],
    boa_kundford_kod       => [ 1 , 0, 146 ],
    boa_kcnford_bel        => [ 9 , 1, 147 ],
    boa_kcnford_kod        => [ 1 , 0, 148 ],
    boa_oevrkford_bel      => [ 9 , 1, 149 ],
    boa_oevrkford_kod      => [ 1 , 0, 150 ],
    boa_sumkford_bel       => [ 9 , 1, 151 ],
    boa_sumkford_kod       => [ 1 , 0, 152 ],
    boa_sumkplac_bel       => [ 9 , 1, 153 ],
    boa_sumkplac_kod       => [ 1 , 0, 154 ],
    boa_sumkassab_bel      => [ 9 , 1, 155 ],
    boa_sumkassab_kod      => [ 1 , 0, 156 ],
    boa_oevromsti_bel      => [ 9 , 1, 157 ],
    boa_oevromsti_kod      => [ 1 , 0, 158 ],
    boa_sumomsti_bel       => [ 9 , 1, 159 ],
    boa_sumomsti_kod       => [ 1 , 0, 160 ],
    boa_sumti_bel          => [ 9 , 1, 161 ],
    boa_sumti_kod          => [ 1 , 0, 162 ],
    boa_aktkap_bel         => [ 9 , 1, 163 ],
    boa_aktkap_kod         => [ 1 , 0, 164 ],
    boa_oekfond_bel        => [ 9 , 1, 165 ],
    boa_oekfond_kod        => [ 1 , 0, 166 ],
    boa_uppskrfond_bel     => [ 9 , 1, 167 ],
    boa_uppskrfond_kod     => [ 1 , 0, 168 ],
    boa_oebunegkap_bel     => [ 9 , 1, 169 ],
    boa_oebunegkap_kod     => [ 1 , 0, 170 ],
    boa_balres_bel         => [ 9 , 1, 171 ],
    boa_balres_kod         => [ 1 , 0, 172 ],
    boa_kcnbidragb_bel     => [ 9 , 1, 173 ],
    boa_kcnbidragb_kod     => [ 1 , 0, 174 ],
    boa_aegtillskb_bel     => [ 9 , 1, 175 ],
    boa_aegtillskb_kod     => [ 1 , 0, 176 ],
    boa_resultatb_bel      => [ 9 , 1, 177 ],
    boa_resultatb_kod      => [ 1 , 0, 178 ],
    boa_sumegkap_bel       => [ 9 , 1, 179 ],
    boa_sumegkap_kod       => [ 1 , 0, 180 ],
    boa_sumobres_bel       => [ 9 , 1, 181 ],
    boa_sumobres_kod       => [ 1 , 0, 182 ],
    boa_minintrb_bel       => [ 9 , 1, 183 ],
    boa_minintrb_kod       => [ 1 , 0, 184 ],
    boa_sumavsaett_bel     => [ 9 , 1, 185 ],
    boa_sumavsaett_kod     => [ 1 , 0, 186 ],
    boa_obllaan_bel        => [ 9 , 1, 187 ],
    boa_obllaan_kod        => [ 1 , 0, 188 ],
    boa_kredlskuld_bel     => [ 9 , 1, 189 ],
    boa_kredlskuld_kod     => [ 1 , 0, 190 ],
    boa_kcnlskuld_bel      => [ 9 , 1, 191 ],
    boa_kcnlskuld_kod      => [ 1 , 0, 192 ],
    boa_oevrlskuld_bel     => [ 9 , 1, 193 ],
    boa_oevrlskuld_kod     => [ 1 , 0, 194 ],
    boa_sumlskuld_bel      => [ 9 , 1, 195 ],
    boa_sumlskuld_kod      => [ 1 , 0, 196 ],
    boa_kredkskuld_bel     => [ 9 , 1, 197 ],
    boa_kredkskuld_kod     => [ 1 , 0, 198 ],
    boa_levskuld_bel       => [ 9 , 1, 199 ],
    boa_levskuld_kod       => [ 1 , 0, 200 ],
    boa_kcnkskuld_bel      => [ 9 , 1, 201 ],
    boa_kcnkskuld_kod      => [ 1 , 0, 202 ],
    boa_oevrkskuld_bel     => [ 9 , 1, 203 ],
    boa_oevrkskuld_kod     => [ 1 , 0, 204 ],
    boa_sumkskuld_bel      => [ 9 , 1, 205 ],
    boa_sumkskuld_kod      => [ 1 , 0, 206 ],
    boa_sumegkapsk_bel     => [ 9 , 1, 207 ],
    boa_sumegkapsk_kod     => [ 1 , 0, 208 ],
    boa_ftgintekn_bel      => [ 9 , 1, 209 ],
    boa_ftgintekn_kod      => [ 1 , 0, 210 ],
    boa_fastintekn_bel     => [ 9 , 1, 211 ],
    boa_fastintekn_kod     => [ 1 , 0, 212 ],
    boa_oevrsaeker_bel     => [ 9 , 1, 213 ],
    boa_oevrsaeker_kod     => [ 1 , 0, 214 ],
    boa_sumsaeker_bel      => [ 9 , 1, 215 ],
    boa_sumsaeker_kod      => [ 1 , 0, 216 ],
    boa_aegtillskv_bel     => [ 9 , 1, 217 ],
    boa_aegtillskv_kod     => [ 1 , 0, 218 ],
    boa_oevransvf_bel      => [ 9 , 1, 219 ],
    boa_oevransvf_kod      => [ 1 , 0, 220 ],
    boa_sumansvf_bel       => [ 9 , 1, 221 ],
    boa_sumansvf_kod       => [ 1 , 0, 222 ],
    boa_anst_ant           => [ 9 , 1, 223 ],
    boa_anst_kod           => [ 1 , 0, 224 ],
    boa_loenstyr_bel       => [ 9 , 1, 225 ],
    boa_loenstyr_kod       => [ 1 , 0, 226 ],
    boa_tantiem_bel        => [ 9 , 1, 227 ],
    boa_tantiem_kod        => [ 1 , 0, 228 ],
    boa_utbetloen_bel      => [ 9 , 1, 229 ],
    boa_utbetloen_kod      => [ 1 , 0, 230 ],
    boa_resloenoev_bel     => [ 9 , 1, 231 ],
    boa_resloenoev_kod     => [ 1 , 0, 232 ],
    boa_socialkost_bel     => [ 9 , 1, 233 ],
    boa_socialkost_kod     => [ 1 , 0, 234 ],
    boa_avvarkost_bel      => [ 9 , 1, 235 ],
    boa_avvarkost_kod      => [ 1 , 0, 236 ],
    boa_avfoerkost_bel     => [ 9 , 1, 237 ],
    boa_avfoerkost_kod     => [ 1 , 0, 238 ],
    boa_avadmkost_bel      => [ 9 , 1, 239 ],
    boa_avadmkost_kod      => [ 1 , 0, 240 ],
    boa_avfoukost_bel      => [ 9 , 1, 241 ],
    boa_avfoukost_kod      => [ 1 , 0, 242 ],
    boa_avroerkost_bel     => [ 9 , 1, 243 ],
    boa_avroerkost_kod     => [ 1 , 0, 244 ],
    boa_avospec_bel        => [ 9 , 1, 245 ],
    boa_avospec_kod        => [ 1 , 0, 246 ],
    boa_bevcheckkr_bel     => [ 9 , 1, 247 ],
    boa_bevcheckkr_kod     => [ 1 , 0, 248 ],
    boa_utncheckkr_bel     => [ 9 , 1, 249 ],
    boa_utncheckkr_kod     => [ 1 , 0, 250 ],
    boa_rtentofinb_bel     => [ 9 , 1, 251 ],
    boa_rtentofinb_kod     => [ 1 , 0, 252 ],
    boa_kommansvf_kod      => [ 1 , 0, 253 ],
    boa_kommsaeker_kod     => [ 1 , 0, 254 ],
    boa_avtvederl_kod      => [ 1 , 0, 255 ],
    boa_konvlaan_kod       => [ 1 , 0, 256 ],
    boa_inkoepkcn_kod      => [ 1 , 0, 257 ],
    boa_ejkcnred_kod       => [ 1 , 0, 258 ],
    boa_revberaett_kod     => [ 2 , 0, 259 ],
    boa_revres_mrk         => [ 1 , 0, 260 ],
    boa_bolprotok_kod      => [ 1 , 0, 261 ],
    boa_arenderegtid       => [ 14, 1, 262 ],
);

sub new() {
    my $self = shift->_classobj();
    return bless $self;
}


sub filename {
    my $self = shift;
    return $filename;
}


# http://search.cpan.org/~gsar/perl-5.6.1/pod/perltootc.pod
# tri-natured: function, class method, or object method
sub _classobj {
    my $obclass = shift || __PACKAGE__;
    my $class   = ref($obclass) || $obclass;
    no strict "refs";   # to convert sym ref to real one
    return \%$class;
} 

for my $datum (keys %{ _classobj() } ) { 
    # turn off strict refs so that we can
    # register a method in the symbol table
    no strict "refs";       
    *$datum = sub {
        use strict "refs";
        my $self = shift->_classobj();
        $self->{$datum} = shift if @_;
        return $self->{$datum};
    }
}



1;