package acib_acitboa;

use strict;
use feature 'unicode_strings';
use export::Testdata;

our @ISA = qw(Testdata);

our $filename = "E719.TESTDATA.ACIB.ACITBOA";

# Indicates field length and if sign should be applied
our %acib_acitboa = (
    boa_org_num            => [ 11, 1 ],
    boa_slut_kod           => [ 1 , 0 ],
    boa_slut_typ           => [ 1 , 0 ],
    boa_redov_typ          => [ 1 , 0 ],
    boa_redov_kod          => [ 1 , 0 ],
    boa_slut_per           => [ 6 , 1 ],
    boa_laengd_ant         => [ 2 , 1 ],
    boa_status_kod         => [ 1 , 0 ],
    boa_slutakt_kod        => [ 1 , 0 ],
    boa_utskr_dat          => [ 8 , 1 ],
    boa_ny_sig             => [ 4 , 0 ],
    boa_trans_dat          => [ 8 , 1 ],
    boa_tid                => [ 6 , 1 ],
    boa_uppd_sig           => [ 4 , 0 ],
    boa_post_status        => [ 1 , 1 ],
    boa_kassett_num        => [ 4 , 1 ],
    boa_filmruta_num       => [ 4 , 1 ],
    boa_ab_status          => [ 1 , 0 ],
    boa_brist_kod          => [ 1 , 0 ],
    boa_kommit_namn        => [ 48, 0 ],
    boa_kommit_org_num     => [ 11, 1 ],
    boa_utdeln_kod         => [ 1 , 0 ],
    boa_utdeln_bel         => [ 9 , 1 ],
    boa_totfakt_bel        => [ 9 , 1 ],
    boa_totfakt_kod        => [ 1 , 0 ],
    boa_foers_bel          => [ 9 , 1 ],
    boa_foers_kod          => [ 1 , 0 ],
    boa_kostvaror_bel      => [ 9 , 1 ],
    boa_kostvaror_kod      => [ 1 , 0 ],
    boa_bruttores_bel      => [ 9 , 1 ],
    boa_bruttores_kod      => [ 1 , 0 ],
    boa_foerskost_bel      => [ 9 , 1 ],
    boa_foerskost_kod      => [ 1 , 0 ],
    boa_admkost_bel        => [ 9 , 1 ],
    boa_admkost_kod        => [ 1 , 0 ],
    boa_foukost_bel        => [ 9 , 1 ],
    boa_foukost_kod        => [ 1 , 0 ],
    boa_jfrpostr2_bel      => [ 9 , 1 ],
    boa_jfrpostr2_kod      => [ 1 , 0 ],
    boa_oeroerinr2_bel     => [ 9 , 1 ],
    boa_oeroerinr2_kod     => [ 1 , 0 ],
    boa_oeroerkor2_bel     => [ 9 , 1 ],
    boa_oeroerkor2_kod     => [ 1 , 0 ],
    boa_foerlager_bel      => [ 9 , 1 ],
    boa_foerlager_kod      => [ 1 , 0 ],
    boa_aktivarb_bel       => [ 9 , 1 ],
    boa_aktivarb_kod       => [ 1 , 0 ],
    boa_oeroerinr1_bel     => [ 9 , 1 ],
    boa_oeroerinr1_kod     => [ 1 , 0 ],
    boa_raavaror_bel       => [ 9 , 1 ],
    boa_raavaror_kod       => [ 1 , 0 ],
    boa_handvaror_bel      => [ 9 , 1 ],
    boa_handvaror_kod      => [ 1 , 0 ],
    boa_oevrextko_bel      => [ 9 , 1 ],
    boa_oevrextko_kod      => [ 1 , 0 ],
    boa_perskost_bel       => [ 9 , 1 ],
    boa_perskost_kod       => [ 1 , 0 ],
    boa_avskrivn_bel       => [ 9 , 1 ],
    boa_avskrivn_kod       => [ 1 , 0 ],
    boa_jfrpostr1_bel      => [ 9 , 1 ],
    boa_jfrpostr1_kod      => [ 1 , 0 ],
    boa_oeroerkor1_bel     => [ 9 , 1 ],
    boa_oeroerkor1_kod     => [ 1 , 0 ],
    boa_roerres_bel        => [ 9 , 1 ],
    boa_roerres_kod        => [ 1 , 0 ],
    boa_resandkcn_bel      => [ 9 , 1 ],
    boa_resandkcn_kod      => [ 1 , 0 ],
    boa_rteintkcn_bel      => [ 9 , 1 ],
    boa_rteintkcn_kod      => [ 1 , 0 ],
    boa_extrteint_bel      => [ 9 , 1 ],
    boa_extrteint_kod      => [ 1 , 0 ],
    boa_oevrfinint_bel     => [ 9 , 1 ],
    boa_oevrfinint_kod     => [ 1 , 0 ],
    boa_rtekostkcn_bel     => [ 9 , 1 ],
    boa_rtekostkcn_kod     => [ 1 , 0 ],
    boa_extrtekost_bel     => [ 9 , 1 ],
    boa_extrtekost_kod     => [ 1 , 0 ],
    boa_oevrfinko_bel      => [ 9 , 1 ],
    boa_oevrfinko_kod      => [ 1 , 0 ],
    boa_jfrfinpost_bel     => [ 9 , 1 ],
    boa_jfrfinpost_kod     => [ 1 , 0 ],
    boa_resfinko_bel       => [ 9 , 1 ],
    boa_resfinko_kod       => [ 1 , 0 ],
    boa_exoint_bel         => [ 9 , 1 ],
    boa_exoint_kod         => [ 1 , 0 ],
    boa_exokost_bel        => [ 9 , 1 ],
    boa_exokost_kod        => [ 1 , 0 ],
    boa_kcnbidragr_bel     => [ 9 , 1 ],
    boa_kcnbidragr_kod     => [ 1 , 0 ],
    boa_aegtillskr_bel     => [ 9 , 1 ],
    boa_aegtillskr_kod     => [ 1 , 0 ],
    boa_bokdisp_bel        => [ 9 , 1 ],
    boa_bokdisp_kod        => [ 1 , 0 ],
    boa_skatt_bel          => [ 9 , 1 ],
    boa_skatt_kod          => [ 1 , 0 ],
    boa_minintrr_bel       => [ 9 , 1 ],
    boa_minintrr_kod       => [ 1 , 0 ],
    boa_resultatr_bel      => [ 9 , 1 ],
    boa_resultatr_kod      => [ 1 , 0 ],
    boa_tecknkap_bel       => [ 9 , 1 ],
    boa_tecknkap_kod       => [ 1 , 0 ],
    boa_balutgfou_bel      => [ 9 , 1 ],
    boa_balutgfou_kod      => [ 1 , 0 ],
    boa_patent_bel         => [ 9 , 1 ],
    boa_patent_kod         => [ 1 , 0 ],
    boa_goodwill_bel       => [ 9 , 1 ],
    boa_goodwill_kod       => [ 1 , 0 ],
    boa_oeimanlti_bel      => [ 9 , 1 ],
    boa_oeimanlti_kod      => [ 1 , 0 ],
    boa_sumimanlti_bel     => [ 9 , 1 ],
    boa_sumimanlti_kod     => [ 1 , 0 ],
    boa_byggmark_bel       => [ 9 , 1 ],
    boa_byggmark_kod       => [ 1 , 0 ],
    boa_mark_bel           => [ 9 , 1 ],
    boa_mark_kod           => [ 1 , 0 ],
    boa_maskiner_bel       => [ 9 , 1 ],
    boa_maskiner_kod       => [ 1 , 0 ],
    boa_invent_bel         => [ 9 , 1 ],
    boa_invent_kod         => [ 1 , 0 ],
    boa_maskinv_bel        => [ 9 , 1 ],
    boa_maskinv_kod        => [ 1 , 0 ],
    boa_eavmatanti_bel     => [ 9 , 1 ],
    boa_eavmatanti_kod     => [ 1 , 0 ],
    boa_avmatanti_bel      => [ 9 , 1 ],
    boa_avmatanti_kod      => [ 1 , 0 ],
    boa_summatanti_bel     => [ 9 , 1 ],
    boa_summatanti_kod     => [ 1 , 0 ],
    boa_andelikcn_bel      => [ 9 , 1 ],
    boa_andelikcn_kod      => [ 1 , 0 ],
    boa_fordrkcn_bel       => [ 9 , 1 ],
    boa_fordrkcn_kod       => [ 1 , 0 ],
    boa_laandelaeg_bel     => [ 9 , 1 ],
    boa_laandelaeg_kod     => [ 1 , 0 ],
    boa_oefinanti_bel      => [ 9 , 1 ],
    boa_oefinanti_kod      => [ 1 , 0 ],
    boa_sumfinanti_bel     => [ 9 , 1 ],
    boa_sumfinanti_kod     => [ 1 , 0 ],
    boa_sumanti_bel        => [ 9 , 1 ],
    boa_sumanti_kod        => [ 1 , 0 ],
    boa_arbfann_bel        => [ 9 , 1 ],
    boa_arbfann_kod        => [ 1 , 0 ],
    boa_oevarulag_bel      => [ 9 , 1 ],
    boa_oevarulag_kod      => [ 1 , 0 ],
    boa_sumvarulag_bel     => [ 9 , 1 ],
    boa_sumvarulag_kod     => [ 1 , 0 ],
    boa_kundford_bel       => [ 9 , 1 ],
    boa_kundford_kod       => [ 1 , 0 ],
    boa_kcnford_bel        => [ 9 , 1 ],
    boa_kcnford_kod        => [ 1 , 0 ],
    boa_oevrkford_bel      => [ 9 , 1 ],
    boa_oevrkford_kod      => [ 1 , 0 ],
    boa_sumkford_bel       => [ 9 , 1 ],
    boa_sumkford_kod       => [ 1 , 0 ],
    boa_sumkplac_bel       => [ 9 , 1 ],
    boa_sumkplac_kod       => [ 1 , 0 ],
    boa_sumkassab_bel      => [ 9 , 1 ],
    boa_sumkassab_kod      => [ 1 , 0 ],
    boa_oevromsti_bel      => [ 9 , 1 ],
    boa_oevromsti_kod      => [ 1 , 0 ],
    boa_sumomsti_bel       => [ 9 , 1 ],
    boa_sumomsti_kod       => [ 1 , 0 ],
    boa_sumti_bel          => [ 9 , 1 ],
    boa_sumti_kod          => [ 1 , 0 ],
    boa_aktkap_bel         => [ 9 , 1 ],
    boa_aktkap_kod         => [ 1 , 0 ],
    boa_oekfond_bel        => [ 9 , 1 ],
    boa_oekfond_kod        => [ 1 , 0 ],
    boa_uppskrfond_bel     => [ 9 , 1 ],
    boa_uppskrfond_kod     => [ 1 , 0 ],
    boa_oebunegkap_bel     => [ 9 , 1 ],
    boa_oebunegkap_kod     => [ 1 , 0 ],
    boa_balres_bel         => [ 9 , 1 ],
    boa_balres_kod         => [ 1 , 0 ],
    boa_kcnbidragb_bel     => [ 9 , 1 ],
    boa_kcnbidragb_kod     => [ 1 , 0 ],
    boa_aegtillskb_bel     => [ 9 , 1 ],
    boa_aegtillskb_kod     => [ 1 , 0 ],
    boa_resultatb_bel      => [ 9 , 1 ],
    boa_resultatb_kod      => [ 1 , 0 ],
    boa_sumegkap_bel       => [ 9 , 1 ],
    boa_sumegkap_kod       => [ 1 , 0 ],
    boa_sumobres_bel       => [ 9 , 1 ],
    boa_sumobres_kod       => [ 1 , 0 ],
    boa_minintrb_bel       => [ 9 , 1 ],
    boa_minintrb_kod       => [ 1 , 0 ],
    boa_sumavsaett_bel     => [ 9 , 1 ],
    boa_sumavsaett_kod     => [ 1 , 0 ],
    boa_obllaan_bel        => [ 9 , 1 ],
    boa_obllaan_kod        => [ 1 , 0 ],
    boa_kredlskuld_bel     => [ 9 , 1 ],
    boa_kredlskuld_kod     => [ 1 , 0 ],
    boa_kcnlskuld_bel      => [ 9 , 1 ],
    boa_kcnlskuld_kod      => [ 1 , 0 ],
    boa_oevrlskuld_bel     => [ 9 , 1 ],
    boa_oevrlskuld_kod     => [ 1 , 0 ],
    boa_sumlskuld_bel      => [ 9 , 1 ],
    boa_sumlskuld_kod      => [ 1 , 0 ],
    boa_kredkskuld_bel     => [ 9 , 1 ],
    boa_kredkskuld_kod     => [ 1 , 0 ],
    boa_levskuld_bel       => [ 9 , 1 ],
    boa_levskuld_kod       => [ 1 , 0 ],
    boa_kcnkskuld_bel      => [ 9 , 1 ],
    boa_kcnkskuld_kod      => [ 1 , 0 ],
    boa_oevrkskuld_bel     => [ 9 , 1 ],
    boa_oevrkskuld_kod     => [ 1 , 0 ],
    boa_sumkskuld_bel      => [ 9 , 1 ],
    boa_sumkskuld_kod      => [ 1 , 0 ],
    boa_sumegkapsk_bel     => [ 9 , 1 ],
    boa_sumegkapsk_kod     => [ 1 , 0 ],
    boa_ftgintekn_bel      => [ 9 , 1 ],
    boa_ftgintekn_kod      => [ 1 , 0 ],
    boa_fastintekn_bel     => [ 9 , 1 ],
    boa_fastintekn_kod     => [ 1 , 0 ],
    boa_oevrsaeker_bel     => [ 9 , 1 ],
    boa_oevrsaeker_kod     => [ 1 , 0 ],
    boa_sumsaeker_bel      => [ 9 , 1 ],
    boa_sumsaeker_kod      => [ 1 , 0 ],
    boa_aegtillskv_bel     => [ 9 , 1 ],
    boa_aegtillskv_kod     => [ 1 , 0 ],
    boa_oevransvf_bel      => [ 9 , 1 ],
    boa_oevransvf_kod      => [ 1 , 0 ],
    boa_sumansvf_bel       => [ 9 , 1 ],
    boa_sumansvf_kod       => [ 1 , 0 ],
    boa_anst_ant           => [ 9 , 1 ],
    boa_anst_kod           => [ 1 , 0 ],
    boa_loenstyr_bel       => [ 9 , 1 ],
    boa_loenstyr_kod       => [ 1 , 0 ],
    boa_tantiem_bel        => [ 9 , 1 ],
    boa_tantiem_kod        => [ 1 , 0 ],
    boa_utbetloen_bel      => [ 9 , 1 ],
    boa_utbetloen_kod      => [ 1 , 0 ],
    boa_resloenoev_bel     => [ 9 , 1 ],
    boa_resloenoev_kod     => [ 1 , 0 ],
    boa_socialkost_bel     => [ 9 , 1 ],
    boa_socialkost_kod     => [ 1 , 0 ],
    boa_avvarkost_bel      => [ 9 , 1 ],
    boa_avvarkost_kod      => [ 1 , 0 ],
    boa_avfoerkost_bel     => [ 9 , 1 ],
    boa_avfoerkost_kod     => [ 1 , 0 ],
    boa_avadmkost_bel      => [ 9 , 1 ],
    boa_avadmkost_kod      => [ 1 , 0 ],
    boa_avfoukost_bel      => [ 9 , 1 ],
    boa_avfoukost_kod      => [ 1 , 0 ],
    boa_avroerkost_bel     => [ 9 , 1 ],
    boa_avroerkost_kod     => [ 1 , 0 ],
    boa_avospec_bel        => [ 9 , 1 ],
    boa_avospec_kod        => [ 1 , 0 ],
    boa_bevcheckkr_bel     => [ 9 , 1 ],
    boa_bevcheckkr_kod     => [ 1 , 0 ],
    boa_utncheckkr_bel     => [ 9 , 1 ],
    boa_utncheckkr_kod     => [ 1 , 0 ],
    boa_rtentofinb_bel     => [ 9 , 1 ],
    boa_rtentofinb_kod     => [ 1 , 0 ],
    boa_kommansvf_kod      => [ 1 , 0 ],
    boa_kommsaeker_kod     => [ 1 , 0 ],
    boa_avtvederl_kod      => [ 1 , 0 ],
    boa_konvlaan_kod       => [ 1 , 0 ],
    boa_inkoepkcn_kod      => [ 1 , 0 ],
    boa_ejkcnred_kod       => [ 1 , 0 ],
    boa_revberaett_kod     => [ 1 , 0 ],
    boa_revres_mrk         => [ 1 , 0 ],
    boa_bolprotok_kod      => [ 1 , 0 ],
    boa_arenderegtid       => [ 14, 1 ],
);

sub new() {
    my $self = shift->_classobj();
    return bless $self;
}


sub filename {
    my $self = shift;
    return $filename;
}


# http://search.cpan.org/~gsar/perl-5.6.1/pod/perltootc.pod
# tri-natured: function, class method, or object method
sub _classobj {
    my $obclass = shift || __PACKAGE__;
    my $class   = ref($obclass) || $obclass;
    no strict "refs";   # to convert sym ref to real one
    return \%$class;
} 

for my $datum (keys %{ _classobj() } ) { 
    # turn off strict refs so that we can
    # register a method in the symbol table
    no strict "refs";       
    *$datum = sub {
        use strict "refs";
        my $self = shift->_classobj();
        $self->{$datum} = shift if @_;
        return $self->{$datum};
    }
}



1;